# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
relative_permalinks: false

# Setup
title:            Mario Larcher
description:      AI blog by Mario Larcher.
url:              https://mnslarcher.github.io
baseurl:          ""

author:
  name:           Mario Larcher
  url:            https://mnslarcher.github.io/about

paginate: 5

# Custom vars
version: 2.1.0

# Optional: link to your GitHub repo
github:
  repo: https://github.com/mnslarcher/mnslarcher.github.io
